export const CATEGORIES = [
  "Groceries",
  "Eating Out",
  "Housing",
  "Utilities",
  "Transportation",
  "Shopping",
  "Health",
  "Entertainment",
  "Subscriptions",
  "Education",
  "Gifts & Donations",
  "Travel",
  "Investments",
  "General",
  "Hobby",
  "Salary",
  "Refunds",
  "Selling Items",
  "Government & Tax",
  "Investment Income",
  "Transfers In",
  "Other Income",
  "Uncategorized"
];
